name: Issue update memo
# If create an issue with "Type:Memo", create a memo from issue.
on:
  issues:
    types: [opened, edited, labeled]

permissions:
  contents: write
  pull-requests: write
  issues: read
jobs:
  update-memo:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'Type:Memo')
    steps:
      - name: checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - name: setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 14
      # Update Memo
      - name: Update Memo
        run: cd actions/update-memo && yarn install && yarn ts-node-transpile-only index-issue.ts
        env:
          ISSUE: ${{ toJSON(github.event.issue) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPDATE_MARKDOWN: true
          DISABLE_NOTIFICATION: "false" # if true, do not comment as reply
      - name: Commit Memo
        uses: EndBug/add-and-commit@dbf207a670f7b7917a3a34f067dcaf7b132cb8d2 # v6.2.0
        with:
          message: "Update Memo"
          push: true
      # Create draft and create pull request
      - name: Create Draft Post
        run: yarn install && yarn ts-node-transpile-only index.ts
        env:
          PAYLOAD: "{}"
          PRIVATE: ${{ github.event.repository.private }}
        working-directory: actions/create-draft-post
      - name: Create Draft Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@18f7dc018cc2cd597073088f7c7591b9d1c02672 # v3.14.0
        with:
          commit-message: Draft Post
          branch: draft
          delete-branch: true
          title: "Draft Post"
          body: |
            - [ ] Write Headline
          labels: |
            Type:Post
      - name: Check Draft Post PR
        run: |
          echo "Pull Request URL - ${STEPS_CPR_OUTPUTS_PULL_REQUEST_URL}"
        env:
          STEPS_CPR_OUTPUTS_PULL_REQUEST_URL: ${{ steps.cpr.outputs.pull-request-url }}