name: Setup Hubmemo

on:
  workflow_dispatch:

permissions:
  issues: write
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - name: setup Node
        with:
          node-version: 14
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      - name: setup labels
        run: npx github-label-sync --labels labels.yml --access-token "$GITHUB_TOKEN" "$GITHUB_REPOSITORY" --allow-added-labels
        working-directory: .github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
