name: test
on: [push, pull_request]
permissions:
  contents: read
jobs:
  test:
    name: "Test on Node.js ${{ matrix.node-version }}"
    runs-on: ubuntu-latest
    if: github.repository.full_name == 'azu/hubmemo' # for testing hubmemo-self
    strategy:
      matrix:
        node-version: [14]
    steps:
      - name: checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - name: setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: yarn install
      - name: Test
        run: |
          cd actions/update-memo && yarn install && yarn test && bash test.local.sh && cd -
          cd actions/create-draft-post && yarn install && bash test.local.sh && cd -
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
