name: test
on: [push, pull_request]
permissions: write-all
jobs:
  test:
    name: "Test on Node.js ${{ matrix.node-version }}"
    runs-on: ubuntu-18.04
    if: github.repository.full_name == 'azu/hubmemo' # for testing hubmemo-self
    strategy:
      matrix:
        node-version: [14]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: yarn install
      - name: Test
        run: |
          cd actions/update-memo && yarn install && yarn test && bash test.local.sh && cd -
          cd actions/create-draft-post && yarn install && bash test.local.sh && cd -
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
